name: Actions CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: actions-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run actionlint
        uses: reviewdog/action-actionlint@d63ba7532e0942965320cd8d73cbae4c7b3c5283 # v1.73.1
        with:
          fail_level: error
      - name: Install ghalint
        env:
          GHALINT_VERSION: v1.6.0
        run: |
          gh release download "$GHALINT_VERSION" -R suzuki-shunsuke/ghalint \
            -p 'ghalint_linux_amd64.tar.gz' -p 'ghalint_checksums.txt'
          grep 'ghalint_linux_amd64.tar.gz$' ghalint_checksums.txt | sha256sum -c -
          tar -xzf ghalint_linux_amd64.tar.gz ghalint
      - name: Run ghalint
        run: ./ghalint run
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false
