name: Verify (Actions)

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: verify-actions-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-actions:
    uses: gopherconjp/actions-toolkit/.github/workflows/verify-actions.yaml@4e79acabd4d513ff3bd0fcf6d94a65a9ff5aee90
    permissions:
      contents: read
      checks: write
